name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Deploy app
        run: ...