name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  runs-on: ubuntu-latest
    deploy:
      steps:
        - uses: actions/checkout@v3
        - uses: akhileshns/heroku-deploy@v3.12.12
          with:
            heroku_api_key: ${{secrets.HEROKU_API_KEY}}
            heroku_app_name: 'git-cicd-kruger'
            heroku_email: ${{secrets.HEROKU_EMAIL}}
            usedocker: true