name: CD

on:
  push:
    branches: ["master"]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name : Build Frontend Files
        run: |
          cd frontend
          npm ci
          npm run build
          cd ..
      - name : Copy .Env file
        run : |
          cd backend
          echo "dbhost = $DB_HOST" >> .env
          echo "dbuser = $DB_USER" >> .env
          echo "dbpassword = $DB_PASSWORD" >> .env
          echo "dbport = $DB_PORT" >> .env
          echo "dbdatabase = $DB_DATABASE" >> .env
          cd ..
        env :
          DB_HOST : ${{ secrets.DB_HOST }}
          DB_USER : ${{ secrets.DB_USER }}
          DB_PASSWORD : ${{ secrets.DB_PASSWORD }}
          DB_PORT : ${{ secrets.DB_PORT }}
          DB_DATABASE : ${{ secrets.DB_DATABASE }}

      - name : deploy to heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'dongcheolparkportfolio'
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          usedocker: true