# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  pull-request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: 'frontend/package-lock.json'
    - name : Build Frontend Files
      run: |
        cd frontend
        npm ci
        npm run build
        ls ../backend/public
        cd ..
    - name : Copy .Env file
      run : |
        cd backend
        echo "dbhost = $DB_HOST" >> .env
        echo "dbuser = $DB_USER" >> .env
        echo "dbpassword = $DB_PASSWORD" >> .env
        echo "dbport = $DB_PORT" >> .env
        echo "dbdatabase = $DB_DATABASE" >> .env
        cd ..
      env :
        DB_HOST : ${{ secrets.DB_HOST }}
        DB_USER : ${{ secrets.DB_USER }}
        DB_PASSWORD : ${{ secrets.DB_PASSWORD }}
        DB_PORT : ${{ secrets.DB_PORT }}
        DB_DATABASE : ${{ secrets.DB_DATABASE }}
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
    # Docker 레지스트리에 대해 로그인하기 위한 GitHub 작업이다.
    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: dongcheolpark
        password: ${{ secrets.TOKEN }}
    # Buildx 로 Docker 이미지를 빌드하고 푸시하는 GitHub 작업이다.
    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ghcr.io/dongcheolpark/devportfolio:latest
